apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csc-rahti-demo-storage
  labels:
    app: csc-rahti-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-csi

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: csc-rahti-demo-netpol
  labels:
    app: csc-rahti-demo
spec:
  podSelector:
    matchLabels:
      app: csc-rahti-demo
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - {}  # Allow all outbound traffic
